### ISSUE TITLE
A question about relationship to the other CR tool.

### ISSUE THREAD

**Issue by rsolomakhin** [jankeromnes/cr#10]
Is this tool related to this other CR tool?
https://code.google.com/p/chromium/wiki/CRUserManual

**Comment by jankeromnes** [comment]
No, both were developed independently (though mine predates the other by about a year), and have overlapping features. Notable differences: mine is a lot simpler (single bash script), but the other `cr` tool has more features, works on windows, and now ships in `depot_tools` by default.
