### ISSUE TITLE
I get an error: make: *** No rule to make target `DumpRenderTree'.  Stop.

### ISSUE THREAD

**Issue by johnjbarton** [jankeromnes/cr#2]
I used `cr clone` and `cr build` to create a fresh copy of chrome. But I can't run make:

```
make BUILDTYPE=Release DumpRenderTree
make: *** No rule to make target `DumpRenderTree'.  Stop.
```

In fact I don't even have a Makefile in the src/ directory.

**Comment by jankeromnes** [comment]
`cr` uses the `ninja` build tool which is incompatible with `make`. Just use:

```
ninja -C out/Release DumpRenderTree -j16
```

Thanks for reporting this, I'll implement `cr DumpRenderTree` soon.
