### ISSUE TITLE
cr breaks webkit-patch upload

### ISSUE THREAD

**Issue by johnjbarton** [jankeromnes/cr#3]
I'm unsure how 
cr update 
works, but apparently it does not use origin/master. Thus if you use |cr update| exclusively to update, origin/master falls behind the webkit remote repo. webkit-patch upload seems to use origin/master as the reference for its diff, at least in part. 

I had trouble with webkit-patch and issued
git fetch
then all was good again.

**Comment by johnjbarton** [comment]
I think the problem is related to this cryptic comment in the man page 
http://linux.die.net/man/1/git-pull
for git pull:
• A parameter <ref> without a colon is equivalent to <ref>: when pulling/fetching, so it merges <ref> into the current branch without storing the remote branch anywhere locally

The note is in reference to :
git pull <options> <repository> <refspec>
where
<refspec>
The format of a <refspec> parameter is an optional plus +, followed by the source ref <src>, followed by a colon :, followed by the destination ref <dst>.

As far as I can tell from the manpage comment and the behavior I see, the command
   git pull --rebase origin master
is an exception to the rule that 
git pull --rebase
is the same as 
git fetch
git rebase

Anyway I think the code would be clearer with
git fetch && git rebase origin/master

**Comment by jankeromnes** [comment]
Agreed, decomposing the fetch and rebase steps seems clearer and from what you found out also more robust. Thanks for finding that, and sorry for taking so long on getting back to you!
